/**
 * Build the two location lists the profile's city picker and `PATCH /auth/me` share.
 *
 *   npm run import:regions
 *
 * 1. `src/data/regionsId.ts` — every Indonesian kabupaten/kota, fetched from emsifa's
 *    static wilayah API, which follows Kepmendagri No. 300.2.2-2430 Tahun 2025. MIT
 *    licensed; the attribution it asks for is carried in `REGIONS_SOURCE`.
 * 2. `src/data/countries.ts` — ISO 3166-1 alpha-2 codes, `ID` excluded. Derived from the
 *    region names Node's own ICU data knows, so nothing is downloaded for it.
 *
 * Both are written as TypeScript modules rather than JSON so `tsc` compiles them into
 * `dist` like any other source — no JSON import attributes, no copy step in the build.
 *
 * Re-run when Kemendagri publishes an update and review the diff like code. A code that
 * vanishes from the source is kept with `retired: true`: no longer offered in the
 * picker, still resolvable for the people who already picked it.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import type { Region } from '../src/lib/locations.js'

const BASE_URL = 'https://www.emsifa.com/api-wilayah-indonesia/v2'
const SOURCE =
  'emsifa/api-wilayah-indonesia (MIT), data per Kepmendagri No. 300.2.2-2430 Tahun 2025 — https://github.com/emsifa/api-wilayah-indonesia'

const DATA_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '../src/data')
const REGIONS_FILE = resolve(DATA_DIR, 'regionsId.ts')
const COUNTRIES_FILE = resolve(DATA_DIR, 'countries.ts')

const HEADER =
  '// Generated by `npm run import:regions` (scripts/importRegions.ts). Do not edit by hand.\n'

interface SourceRow {
  id: string
  name: string
}

async function getData(path: string): Promise<SourceRow[]> {
  const res = await fetch(`${BASE_URL}/${path}`)
  if (!res.ok) throw new Error(`GET ${path} → ${res.status}`)
  const body = (await res.json()) as { data?: SourceRow[] }
  if (!Array.isArray(body.data)) throw new Error(`GET ${path} → no data array`)
  return body.data
}

/**
 * Kemendagri numbers kota 71–99 and kabupaten 01–69 within a province, so the type comes
 * from the code. The name is checked against it, and a disagreement stops the import
 * rather than guessing.
 */
function typeFor(row: SourceRow): Region['type'] {
  const serial = Number(row.id.split('.')[1])
  const type = serial >= 71 ? 'kota' : 'kabupaten'
  const prefix = type === 'kota' ? /^Kota\b/ : /^Kabupaten\b/
  if (!prefix.test(row.name)) {
    throw new Error(`${row.id} "${row.name}" doesn't read as a ${type}`)
  }
  return type
}

/** "Kota Bandung" → "Bandung", "Kabupaten Bandung" → "Kab. Bandung", and Jakarta's
 * administrative ones ("Kota Administrasi Jakarta Selatan") → "Jakarta Selatan". */
function shortNameFor(name: string, type: Region['type']): string {
  if (type === 'kota') return name.replace(/^Kota (Administrasi )?/, '')
  return `Kab. ${name.replace(/^Kabupaten (Administrasi )?/, '')}`
}

async function readPrevious(): Promise<readonly Region[]> {
  try {
    const previous = (await import(pathToFileURL(REGIONS_FILE).href)) as {
      REGIONS?: readonly Region[]
    }
    return previous.REGIONS ?? []
  } catch {
    return []
  }
}

async function importRegions(): Promise<void> {
  const provinces = await getData('provinces.json')
  const regions: Region[] = []

  for (const province of provinces) {
    const rows = await getData(`regencies/${province.id}.json`)
    for (const row of rows) {
      const type = typeFor(row)
      regions.push({
        code: row.id,
        name: row.name,
        shortName: shortNameFor(row.name, type),
        type,
        provinceCode: province.id,
        provinceName: province.name,
      })
    }
  }

  const current = new Set(regions.map((r) => r.code))
  const retired = (await readPrevious())
    .filter((r) => !current.has(r.code))
    .map((r): Region => ({ ...r, retired: true }))

  const all = [...regions, ...retired].sort((a, b) => a.code.localeCompare(b.code))
  await writeFile(
    REGIONS_FILE,
    HEADER +
      "import type { Region } from '../lib/locations.js'\n\n" +
      `export const REGIONS_SOURCE = ${JSON.stringify(SOURCE)}\n\n` +
      `export const REGIONS_IMPORTED_AT = ${JSON.stringify(new Date().toISOString())}\n\n` +
      `export const REGIONS: readonly Region[] = ${JSON.stringify(all, null, 2)}\n`,
  )

  const kota = regions.filter((r) => r.type === 'kota').length
  console.log(
    `regionsId.ts: ${provinces.length} provinces, ${regions.length} active ` +
      `(${regions.length - kota} kabupaten, ${kota} kota), ${retired.length} retired`,
  )
}

/**
 * Two-letter codes ICU names that aren't countries a person lives in: macro-regions,
 * exceptionally reserved codes, ones withdrawn from ISO 3166-1, and old aliases ICU
 * still resolves to a current country (DY → Benin, UK → United Kingdom, …), which
 * would otherwise list that country twice.
 */
const NOT_COUNTRIES = new Set([
  'ID',
  'EU',
  'EZ',
  'UN',
  'QO',
  'ZZ',
  'AC',
  'CP',
  'CQ',
  'DG',
  'EA',
  'IC',
  'TA',
  'AN',
  'BU',
  'CS',
  'DD',
  'FX',
  'NT',
  'SU',
  'TP',
  'YD',
  'YU',
  'ZR',
  'XA',
  'XB',
  'DY',
  'HV',
  'NH',
  'RH',
  'UK',
  'VD',
])

async function importCountries(): Promise<void> {
  const names = new Intl.DisplayNames(['en'], { type: 'region', fallback: 'none' })
  const codes: string[] = []
  for (let a = 65; a <= 90; a++) {
    for (let b = 65; b <= 90; b++) {
      const code = String.fromCharCode(a, b)
      if (NOT_COUNTRIES.has(code)) continue
      if (names.of(code)) codes.push(code)
    }
  }
  await writeFile(
    COUNTRIES_FILE,
    `${HEADER}\nexport const COUNTRY_CODES: readonly string[] = ${JSON.stringify(codes)}\n`,
  )
  console.log(`countries.ts: ${codes.length} codes`)
}

await mkdir(DATA_DIR, { recursive: true })
await importRegions()
await importCountries()
