// Generated by `npm run import:regions` (scripts/importRegions.ts). Do not edit by hand.
import type { Region } from '../lib/locations.js'

export const REGIONS_SOURCE = "emsifa/api-wilayah-indonesia (MIT), data per Kepmendagri No. 300.2.2-2430 Tahun 2025 — https://github.com/emsifa/api-wilayah-indonesia"

export const REGIONS_IMPORTED_AT = "2026-09-14T08:14:41.268Z"

export const REGIONS: readonly Region[] = [
  {
    "code": "11.01",
    "name": "Kabupaten Aceh Selatan",
    "shortName": "Kab. Aceh Selatan",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.02",
    "name": "Kabupaten Aceh Tenggara",
    "shortName": "Kab. Aceh Tenggara",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.03",
    "name": "Kabupaten Aceh Timur",
    "shortName": "Kab. Aceh Timur",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.04",
    "name": "Kabupaten Aceh Tengah",
    "shortName": "Kab. Aceh Tengah",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.05",
    "name": "Kabupaten Aceh Barat",
    "shortName": "Kab. Aceh Barat",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.06",
    "name": "Kabupaten Aceh Besar",
    "shortName": "Kab. Aceh Besar",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.07",
    "name": "Kabupaten Pidie",
    "shortName": "Kab. Pidie",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.08",
    "name": "Kabupaten Aceh Utara",
    "shortName": "Kab. Aceh Utara",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.09",
    "name": "Kabupaten Simeulue",
    "shortName": "Kab. Simeulue",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.10",
    "name": "Kabupaten Aceh Singkil",
    "shortName": "Kab. Aceh Singkil",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.11",
    "name": "Kabupaten Bireuen",
    "shortName": "Kab. Bireuen",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.12",
    "name": "Kabupaten Aceh Barat Daya",
    "shortName": "Kab. Aceh Barat Daya",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.13",
    "name": "Kabupaten Gayo Lues",
    "shortName": "Kab. Gayo Lues",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.14",
    "name": "Kabupaten Aceh Jaya",
    "shortName": "Kab. Aceh Jaya",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.15",
    "name": "Kabupaten Nagan Raya",
    "shortName": "Kab. Nagan Raya",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.16",
    "name": "Kabupaten Aceh Tamiang",
    "shortName": "Kab. Aceh Tamiang",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.17",
    "name": "Kabupaten Bener Meriah",
    "shortName": "Kab. Bener Meriah",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.18",
    "name": "Kabupaten Pidie Jaya",
    "shortName": "Kab. Pidie Jaya",
    "type": "kabupaten",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.71",
    "name": "Kota Banda Aceh",
    "shortName": "Banda Aceh",
    "type": "kota",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.72",
    "name": "Kota Sabang",
    "shortName": "Sabang",
    "type": "kota",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.73",
    "name": "Kota Lhokseumawe",
    "shortName": "Lhokseumawe",
    "type": "kota",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.74",
    "name": "Kota Langsa",
    "shortName": "Langsa",
    "type": "kota",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "11.75",
    "name": "Kota Subulussalam",
    "shortName": "Subulussalam",
    "type": "kota",
    "provinceCode": "11",
    "provinceName": "Aceh"
  },
  {
    "code": "12.01",
    "name": "Kabupaten Tapanuli Tengah",
    "shortName": "Kab. Tapanuli Tengah",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.02",
    "name": "Kabupaten Tapanuli Utara",
    "shortName": "Kab. Tapanuli Utara",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.03",
    "name": "Kabupaten Tapanuli Selatan",
    "shortName": "Kab. Tapanuli Selatan",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.04",
    "name": "Kabupaten Nias",
    "shortName": "Kab. Nias",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.05",
    "name": "Kabupaten Langkat",
    "shortName": "Kab. Langkat",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.06",
    "name": "Kabupaten Karo",
    "shortName": "Kab. Karo",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.07",
    "name": "Kabupaten Deli Serdang",
    "shortName": "Kab. Deli Serdang",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.08",
    "name": "Kabupaten Simalungun",
    "shortName": "Kab. Simalungun",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.09",
    "name": "Kabupaten Asahan",
    "shortName": "Kab. Asahan",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.10",
    "name": "Kabupaten Labuhanbatu",
    "shortName": "Kab. Labuhanbatu",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.11",
    "name": "Kabupaten Dairi",
    "shortName": "Kab. Dairi",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.12",
    "name": "Kabupaten Toba",
    "shortName": "Kab. Toba",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.13",
    "name": "Kabupaten Mandailing Natal",
    "shortName": "Kab. Mandailing Natal",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.14",
    "name": "Kabupaten Nias Selatan",
    "shortName": "Kab. Nias Selatan",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.15",
    "name": "Kabupaten Pakpak Bharat",
    "shortName": "Kab. Pakpak Bharat",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.16",
    "name": "Kabupaten Humbang Hasundutan",
    "shortName": "Kab. Humbang Hasundutan",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.17",
    "name": "Kabupaten Samosir",
    "shortName": "Kab. Samosir",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.18",
    "name": "Kabupaten Serdang Bedagai",
    "shortName": "Kab. Serdang Bedagai",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.19",
    "name": "Kabupaten Batu Bara",
    "shortName": "Kab. Batu Bara",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.20",
    "name": "Kabupaten Padang Lawas Utara",
    "shortName": "Kab. Padang Lawas Utara",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.21",
    "name": "Kabupaten Padang Lawas",
    "shortName": "Kab. Padang Lawas",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.22",
    "name": "Kabupaten Labuhanbatu Selatan",
    "shortName": "Kab. Labuhanbatu Selatan",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.23",
    "name": "Kabupaten Labuhanbatu Utara",
    "shortName": "Kab. Labuhanbatu Utara",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.24",
    "name": "Kabupaten Nias Utara",
    "shortName": "Kab. Nias Utara",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.25",
    "name": "Kabupaten Nias Barat",
    "shortName": "Kab. Nias Barat",
    "type": "kabupaten",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.71",
    "name": "Kota Medan",
    "shortName": "Medan",
    "type": "kota",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.72",
    "name": "Kota Pematangsiantar",
    "shortName": "Pematangsiantar",
    "type": "kota",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.73",
    "name": "Kota Sibolga",
    "shortName": "Sibolga",
    "type": "kota",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.74",
    "name": "Kota Tanjungbalai",
    "shortName": "Tanjungbalai",
    "type": "kota",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.75",
    "name": "Kota Binjai",
    "shortName": "Binjai",
    "type": "kota",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.76",
    "name": "Kota Tebing Tinggi",
    "shortName": "Tebing Tinggi",
    "type": "kota",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.77",
    "name": "Kota Padangsidimpuan",
    "shortName": "Padangsidimpuan",
    "type": "kota",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "12.78",
    "name": "Kota Gunungsitoli",
    "shortName": "Gunungsitoli",
    "type": "kota",
    "provinceCode": "12",
    "provinceName": "Sumatera Utara"
  },
  {
    "code": "13.01",
    "name": "Kabupaten Pesisir Selatan",
    "shortName": "Kab. Pesisir Selatan",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.02",
    "name": "Kabupaten Solok",
    "shortName": "Kab. Solok",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.03",
    "name": "Kabupaten Sijunjung",
    "shortName": "Kab. Sijunjung",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.04",
    "name": "Kabupaten Tanah Datar",
    "shortName": "Kab. Tanah Datar",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.05",
    "name": "Kabupaten Padang Pariaman",
    "shortName": "Kab. Padang Pariaman",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.06",
    "name": "Kabupaten Agam",
    "shortName": "Kab. Agam",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.07",
    "name": "Kabupaten Lima Puluh Kota",
    "shortName": "Kab. Lima Puluh Kota",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.08",
    "name": "Kabupaten Pasaman",
    "shortName": "Kab. Pasaman",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.09",
    "name": "Kabupaten Kepulauan Mentawai",
    "shortName": "Kab. Kepulauan Mentawai",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.10",
    "name": "Kabupaten Dharmasraya",
    "shortName": "Kab. Dharmasraya",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.11",
    "name": "Kabupaten Solok Selatan",
    "shortName": "Kab. Solok Selatan",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.12",
    "name": "Kabupaten Pasaman Barat",
    "shortName": "Kab. Pasaman Barat",
    "type": "kabupaten",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.71",
    "name": "Kota Padang",
    "shortName": "Padang",
    "type": "kota",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.72",
    "name": "Kota Solok",
    "shortName": "Solok",
    "type": "kota",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.73",
    "name": "Kota Sawahlunto",
    "shortName": "Sawahlunto",
    "type": "kota",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.74",
    "name": "Kota Padang Panjang",
    "shortName": "Padang Panjang",
    "type": "kota",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.75",
    "name": "Kota Bukittinggi",
    "shortName": "Bukittinggi",
    "type": "kota",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.76",
    "name": "Kota Payakumbuh",
    "shortName": "Payakumbuh",
    "type": "kota",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "13.77",
    "name": "Kota Pariaman",
    "shortName": "Pariaman",
    "type": "kota",
    "provinceCode": "13",
    "provinceName": "Sumatera Barat"
  },
  {
    "code": "14.01",
    "name": "Kabupaten Kampar",
    "shortName": "Kab. Kampar",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.02",
    "name": "Kabupaten Indragiri Hulu",
    "shortName": "Kab. Indragiri Hulu",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.03",
    "name": "Kabupaten Bengkalis",
    "shortName": "Kab. Bengkalis",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.04",
    "name": "Kabupaten Indragiri Hilir",
    "shortName": "Kab. Indragiri Hilir",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.05",
    "name": "Kabupaten Pelalawan",
    "shortName": "Kab. Pelalawan",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.06",
    "name": "Kabupaten Rokan Hulu",
    "shortName": "Kab. Rokan Hulu",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.07",
    "name": "Kabupaten Rokan Hilir",
    "shortName": "Kab. Rokan Hilir",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.08",
    "name": "Kabupaten Siak",
    "shortName": "Kab. Siak",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.09",
    "name": "Kabupaten Kuantan Singingi",
    "shortName": "Kab. Kuantan Singingi",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.10",
    "name": "Kabupaten Kepulauan Meranti",
    "shortName": "Kab. Kepulauan Meranti",
    "type": "kabupaten",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.71",
    "name": "Kota Pekanbaru",
    "shortName": "Pekanbaru",
    "type": "kota",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "14.72",
    "name": "Kota Dumai",
    "shortName": "Dumai",
    "type": "kota",
    "provinceCode": "14",
    "provinceName": "Riau"
  },
  {
    "code": "15.01",
    "name": "Kabupaten Kerinci",
    "shortName": "Kab. Kerinci",
    "type": "kabupaten",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.02",
    "name": "Kabupaten  Merangin",
    "shortName": "Kab.  Merangin",
    "type": "kabupaten",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.03",
    "name": "Kabupaten Sarolangun",
    "shortName": "Kab. Sarolangun",
    "type": "kabupaten",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.04",
    "name": "Kabupaten Batanghari",
    "shortName": "Kab. Batanghari",
    "type": "kabupaten",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.05",
    "name": "Kabupaten  Muaro Jambi",
    "shortName": "Kab.  Muaro Jambi",
    "type": "kabupaten",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.06",
    "name": "Kabupaten Tanjung Jabung Barat",
    "shortName": "Kab. Tanjung Jabung Barat",
    "type": "kabupaten",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.07",
    "name": "Kabupaten Tanjung Jabung Timur",
    "shortName": "Kab. Tanjung Jabung Timur",
    "type": "kabupaten",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.08",
    "name": "Kabupaten Bungo",
    "shortName": "Kab. Bungo",
    "type": "kabupaten",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.09",
    "name": "Kabupaten Tebo",
    "shortName": "Kab. Tebo",
    "type": "kabupaten",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.71",
    "name": "Kota Jambi",
    "shortName": "Jambi",
    "type": "kota",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "15.72",
    "name": "Kota Sungai Penuh",
    "shortName": "Sungai Penuh",
    "type": "kota",
    "provinceCode": "15",
    "provinceName": "Jambi"
  },
  {
    "code": "16.01",
    "name": "Kabupaten Ogan Komering Ulu",
    "shortName": "Kab. Ogan Komering Ulu",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.02",
    "name": "Kabupaten Ogan Komering",
    "shortName": "Kab. Ogan Komering",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.03",
    "name": "Kabupaten Muara Enim",
    "shortName": "Kab. Muara Enim",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.04",
    "name": "Kabupaten Lahat",
    "shortName": "Kab. Lahat",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.05",
    "name": "Kabupaten Musi Rawas",
    "shortName": "Kab. Musi Rawas",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.06",
    "name": "Kabupaten Musi Banyuasin",
    "shortName": "Kab. Musi Banyuasin",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.07",
    "name": "Kabupaten Banyuasin",
    "shortName": "Kab. Banyuasin",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.08",
    "name": "Kabupaten Ogan Komering Ulu Timur",
    "shortName": "Kab. Ogan Komering Ulu Timur",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.09",
    "name": "Kabupaten Ogan Komering Ulu Selatan",
    "shortName": "Kab. Ogan Komering Ulu Selatan",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.10",
    "name": "Kabupaten Ogan Ilir",
    "shortName": "Kab. Ogan Ilir",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.11",
    "name": "Kabupaten Empat Lawang",
    "shortName": "Kab. Empat Lawang",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.12",
    "name": "Kabupaten Penukal Abab Lematang Ilir",
    "shortName": "Kab. Penukal Abab Lematang Ilir",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.13",
    "name": "Kabupaten Musi Rawas Utara",
    "shortName": "Kab. Musi Rawas Utara",
    "type": "kabupaten",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.71",
    "name": "Kota Palembang",
    "shortName": "Palembang",
    "type": "kota",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.72",
    "name": "Kota Pagar Alam",
    "shortName": "Pagar Alam",
    "type": "kota",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.73",
    "name": "Kota Lubuk Linggau",
    "shortName": "Lubuk Linggau",
    "type": "kota",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "16.74",
    "name": "Kota Prabumulih",
    "shortName": "Prabumulih",
    "type": "kota",
    "provinceCode": "16",
    "provinceName": "Sumatera Selatan"
  },
  {
    "code": "17.01",
    "name": "Kabupaten Bengkulu Selatan",
    "shortName": "Kab. Bengkulu Selatan",
    "type": "kabupaten",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "17.02",
    "name": "Kabupaten Rejang Lebong",
    "shortName": "Kab. Rejang Lebong",
    "type": "kabupaten",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "17.03",
    "name": "Kabupaten Bengkulu Utara",
    "shortName": "Kab. Bengkulu Utara",
    "type": "kabupaten",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "17.04",
    "name": "Kabupaten Kaur",
    "shortName": "Kab. Kaur",
    "type": "kabupaten",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "17.05",
    "name": "Kabupaten Seluma",
    "shortName": "Kab. Seluma",
    "type": "kabupaten",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "17.06",
    "name": "Kabupaten Mukomuko",
    "shortName": "Kab. Mukomuko",
    "type": "kabupaten",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "17.07",
    "name": "Kabupaten Lebong",
    "shortName": "Kab. Lebong",
    "type": "kabupaten",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "17.08",
    "name": "Kabupaten Kepahiang",
    "shortName": "Kab. Kepahiang",
    "type": "kabupaten",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "17.09",
    "name": "Kabupaten Bengkulu Tengah",
    "shortName": "Kab. Bengkulu Tengah",
    "type": "kabupaten",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "17.71",
    "name": "Kota Bengkulu",
    "shortName": "Bengkulu",
    "type": "kota",
    "provinceCode": "17",
    "provinceName": "Bengkulu"
  },
  {
    "code": "18.01",
    "name": "Kabupaten Lampung Selatan",
    "shortName": "Kab. Lampung Selatan",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.02",
    "name": "Kabupaten Lampung Tengah",
    "shortName": "Kab. Lampung Tengah",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.03",
    "name": "Kabupaten Lampung Utara",
    "shortName": "Kab. Lampung Utara",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.04",
    "name": "Kabupaten Lampung Barat",
    "shortName": "Kab. Lampung Barat",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.05",
    "name": "Kabupaten Tulang Bawang",
    "shortName": "Kab. Tulang Bawang",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.06",
    "name": "Kabupaten Tanggamus",
    "shortName": "Kab. Tanggamus",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.07",
    "name": "Kabupaten Lampung Timur",
    "shortName": "Kab. Lampung Timur",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.08",
    "name": "Kabupaten Way Kanan",
    "shortName": "Kab. Way Kanan",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.09",
    "name": "Kabupaten Pesawaran",
    "shortName": "Kab. Pesawaran",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.10",
    "name": "Kabupaten Pringsewu",
    "shortName": "Kab. Pringsewu",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.11",
    "name": "Kabupaten Mesuji",
    "shortName": "Kab. Mesuji",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.12",
    "name": "Kabupaten Tulang Bawang Barat",
    "shortName": "Kab. Tulang Bawang Barat",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.13",
    "name": "Kabupaten Pesisir Barat",
    "shortName": "Kab. Pesisir Barat",
    "type": "kabupaten",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.71",
    "name": "Kota Bandar Lampung",
    "shortName": "Bandar Lampung",
    "type": "kota",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "18.72",
    "name": "Kota Metro",
    "shortName": "Metro",
    "type": "kota",
    "provinceCode": "18",
    "provinceName": "Lampung"
  },
  {
    "code": "19.01",
    "name": "Kabupaten Bangka",
    "shortName": "Kab. Bangka",
    "type": "kabupaten",
    "provinceCode": "19",
    "provinceName": "Kepulauan Bangka Belitung"
  },
  {
    "code": "19.02",
    "name": "Kabupaten Belitung",
    "shortName": "Kab. Belitung",
    "type": "kabupaten",
    "provinceCode": "19",
    "provinceName": "Kepulauan Bangka Belitung"
  },
  {
    "code": "19.03",
    "name": "Kabupaten Bangka Selatan",
    "shortName": "Kab. Bangka Selatan",
    "type": "kabupaten",
    "provinceCode": "19",
    "provinceName": "Kepulauan Bangka Belitung"
  },
  {
    "code": "19.04",
    "name": "Kabupaten Bangka Tengah",
    "shortName": "Kab. Bangka Tengah",
    "type": "kabupaten",
    "provinceCode": "19",
    "provinceName": "Kepulauan Bangka Belitung"
  },
  {
    "code": "19.05",
    "name": "Kabupaten Bangka Barat",
    "shortName": "Kab. Bangka Barat",
    "type": "kabupaten",
    "provinceCode": "19",
    "provinceName": "Kepulauan Bangka Belitung"
  },
  {
    "code": "19.06",
    "name": "Kabupaten Belitung Timur",
    "shortName": "Kab. Belitung Timur",
    "type": "kabupaten",
    "provinceCode": "19",
    "provinceName": "Kepulauan Bangka Belitung"
  },
  {
    "code": "19.71",
    "name": "Kota Pangkal Pinang",
    "shortName": "Pangkal Pinang",
    "type": "kota",
    "provinceCode": "19",
    "provinceName": "Kepulauan Bangka Belitung"
  },
  {
    "code": "21.01",
    "name": "Kabupaten Bintan",
    "shortName": "Kab. Bintan",
    "type": "kabupaten",
    "provinceCode": "21",
    "provinceName": "Kepulauan Riau"
  },
  {
    "code": "21.02",
    "name": "Kabupaten Karimun",
    "shortName": "Kab. Karimun",
    "type": "kabupaten",
    "provinceCode": "21",
    "provinceName": "Kepulauan Riau"
  },
  {
    "code": "21.03",
    "name": "Kabupaten Natuna",
    "shortName": "Kab. Natuna",
    "type": "kabupaten",
    "provinceCode": "21",
    "provinceName": "Kepulauan Riau"
  },
  {
    "code": "21.04",
    "name": "Kabupaten Lingga",
    "shortName": "Kab. Lingga",
    "type": "kabupaten",
    "provinceCode": "21",
    "provinceName": "Kepulauan Riau"
  },
  {
    "code": "21.05",
    "name": "Kabupaten Kepulauan Anambas",
    "shortName": "Kab. Kepulauan Anambas",
    "type": "kabupaten",
    "provinceCode": "21",
    "provinceName": "Kepulauan Riau"
  },
  {
    "code": "21.71",
    "name": "Kota Batam",
    "shortName": "Batam",
    "type": "kota",
    "provinceCode": "21",
    "provinceName": "Kepulauan Riau"
  },
  {
    "code": "21.72",
    "name": "Kota Tanjung Pinang",
    "shortName": "Tanjung Pinang",
    "type": "kota",
    "provinceCode": "21",
    "provinceName": "Kepulauan Riau"
  },
  {
    "code": "31.01",
    "name": "Kabupaten Administrasi Kepulauan Seribu",
    "shortName": "Kab. Kepulauan Seribu",
    "type": "kabupaten",
    "provinceCode": "31",
    "provinceName": "Daerah Khusus Ibukota Jakarta"
  },
  {
    "code": "31.71",
    "name": "Kota Administrasi Jakarta Pusat",
    "shortName": "Jakarta Pusat",
    "type": "kota",
    "provinceCode": "31",
    "provinceName": "Daerah Khusus Ibukota Jakarta"
  },
  {
    "code": "31.72",
    "name": "Kota Administrasi Jakarta Utara",
    "shortName": "Jakarta Utara",
    "type": "kota",
    "provinceCode": "31",
    "provinceName": "Daerah Khusus Ibukota Jakarta"
  },
  {
    "code": "31.73",
    "name": "Kota Administrasi Jakarta Barat",
    "shortName": "Jakarta Barat",
    "type": "kota",
    "provinceCode": "31",
    "provinceName": "Daerah Khusus Ibukota Jakarta"
  },
  {
    "code": "31.74",
    "name": "Kota Administrasi Jakarta Selatan",
    "shortName": "Jakarta Selatan",
    "type": "kota",
    "provinceCode": "31",
    "provinceName": "Daerah Khusus Ibukota Jakarta"
  },
  {
    "code": "31.75",
    "name": "Kota Administrasi Jakarta Timur",
    "shortName": "Jakarta Timur",
    "type": "kota",
    "provinceCode": "31",
    "provinceName": "Daerah Khusus Ibukota Jakarta"
  },
  {
    "code": "32.01",
    "name": "Kabupaten Bogor",
    "shortName": "Kab. Bogor",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.02",
    "name": "Kabupaten Sukabumi",
    "shortName": "Kab. Sukabumi",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.03",
    "name": "Kabupaten Cianjur",
    "shortName": "Kab. Cianjur",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.04",
    "name": "Kabupaten Bandung",
    "shortName": "Kab. Bandung",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.05",
    "name": "Kabupaten Garut",
    "shortName": "Kab. Garut",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.06",
    "name": "Kabupaten Tasikmalaya",
    "shortName": "Kab. Tasikmalaya",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.07",
    "name": "Kabupaten Ciamis",
    "shortName": "Kab. Ciamis",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.08",
    "name": "Kabupaten Kuningan",
    "shortName": "Kab. Kuningan",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.09",
    "name": "Kabupaten Cirebon",
    "shortName": "Kab. Cirebon",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.10",
    "name": "Kabupaten Majalengka",
    "shortName": "Kab. Majalengka",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.11",
    "name": "Kabupaten Sumedang",
    "shortName": "Kab. Sumedang",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.12",
    "name": "Kabupaten Indramayu",
    "shortName": "Kab. Indramayu",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.13",
    "name": "Kabupaten Subang",
    "shortName": "Kab. Subang",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.14",
    "name": "Kabupaten Purwakarta",
    "shortName": "Kab. Purwakarta",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.15",
    "name": "Kabupaten Karawang",
    "shortName": "Kab. Karawang",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.16",
    "name": "Kabupaten Bekasi",
    "shortName": "Kab. Bekasi",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.17",
    "name": "Kabupaten Bandung Barat",
    "shortName": "Kab. Bandung Barat",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.18",
    "name": "Kabupaten Pangandaran",
    "shortName": "Kab. Pangandaran",
    "type": "kabupaten",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.71",
    "name": "Kota Bogor",
    "shortName": "Bogor",
    "type": "kota",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.72",
    "name": "Kota Sukabumi",
    "shortName": "Sukabumi",
    "type": "kota",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.73",
    "name": "Kota Bandung",
    "shortName": "Bandung",
    "type": "kota",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.74",
    "name": "Kota Cirebon",
    "shortName": "Cirebon",
    "type": "kota",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.75",
    "name": "Kota Bekasi",
    "shortName": "Bekasi",
    "type": "kota",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.76",
    "name": "Kota Depok",
    "shortName": "Depok",
    "type": "kota",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.77",
    "name": "Kota Cimahi",
    "shortName": "Cimahi",
    "type": "kota",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.78",
    "name": "Kota Tasikmalaya",
    "shortName": "Tasikmalaya",
    "type": "kota",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "32.79",
    "name": "Kota Banjar",
    "shortName": "Banjar",
    "type": "kota",
    "provinceCode": "32",
    "provinceName": "Jawa Barat"
  },
  {
    "code": "33.01",
    "name": "Kabupaten Cilacap",
    "shortName": "Kab. Cilacap",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.02",
    "name": "Kabupaten Banyumas",
    "shortName": "Kab. Banyumas",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.03",
    "name": "Kabupaten Purbalingga",
    "shortName": "Kab. Purbalingga",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.04",
    "name": "Kabupaten Banjarnegara",
    "shortName": "Kab. Banjarnegara",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.05",
    "name": "Kabupaten Kebumen",
    "shortName": "Kab. Kebumen",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.06",
    "name": "Kabupaten Purworejo",
    "shortName": "Kab. Purworejo",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.07",
    "name": "Kabupaten Wonosobo",
    "shortName": "Kab. Wonosobo",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.08",
    "name": "Kabupaten Magelang",
    "shortName": "Kab. Magelang",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.09",
    "name": "Kabupaten Boyolali",
    "shortName": "Kab. Boyolali",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.10",
    "name": "Kabupaten Klaten",
    "shortName": "Kab. Klaten",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.11",
    "name": "Kabupaten Sukoharjo",
    "shortName": "Kab. Sukoharjo",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.12",
    "name": "Kabupaten Wonogiri",
    "shortName": "Kab. Wonogiri",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.13",
    "name": "Kabupaten Karanganyar",
    "shortName": "Kab. Karanganyar",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.14",
    "name": "Kabupaten Sragen",
    "shortName": "Kab. Sragen",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.15",
    "name": "Kabupaten Grobogan",
    "shortName": "Kab. Grobogan",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.16",
    "name": "Kabupaten Blora",
    "shortName": "Kab. Blora",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.17",
    "name": "Kabupaten Rembang",
    "shortName": "Kab. Rembang",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.18",
    "name": "Kabupaten Pati",
    "shortName": "Kab. Pati",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.19",
    "name": "Kabupaten Kudus",
    "shortName": "Kab. Kudus",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.20",
    "name": "Kabupaten Jepara",
    "shortName": "Kab. Jepara",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.21",
    "name": "Kabupaten Demak",
    "shortName": "Kab. Demak",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.22",
    "name": "Kabupaten Semarang",
    "shortName": "Kab. Semarang",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.23",
    "name": "Kabupaten Temanggung",
    "shortName": "Kab. Temanggung",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.24",
    "name": "Kabupaten Kendal",
    "shortName": "Kab. Kendal",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.25",
    "name": "Kabupaten Batang",
    "shortName": "Kab. Batang",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.26",
    "name": "Kabupaten Pekalongan",
    "shortName": "Kab. Pekalongan",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.27",
    "name": "Kabupaten Pemalang",
    "shortName": "Kab. Pemalang",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.28",
    "name": "Kabupaten Tegal",
    "shortName": "Kab. Tegal",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.29",
    "name": "Kabupaten Brebes",
    "shortName": "Kab. Brebes",
    "type": "kabupaten",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.71",
    "name": "Kota Magelang",
    "shortName": "Magelang",
    "type": "kota",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.72",
    "name": "Kota Surakarta",
    "shortName": "Surakarta",
    "type": "kota",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.73",
    "name": "Kota Salatiga",
    "shortName": "Salatiga",
    "type": "kota",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.74",
    "name": "Kota Semarang",
    "shortName": "Semarang",
    "type": "kota",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.75",
    "name": "Kota Pekalongan",
    "shortName": "Pekalongan",
    "type": "kota",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "33.76",
    "name": "Kota Tegal",
    "shortName": "Tegal",
    "type": "kota",
    "provinceCode": "33",
    "provinceName": "Jawa Tengah"
  },
  {
    "code": "34.01",
    "name": "Kabupaten Kulon Progo",
    "shortName": "Kab. Kulon Progo",
    "type": "kabupaten",
    "provinceCode": "34",
    "provinceName": "Daerah Istimewa Yogyakarta"
  },
  {
    "code": "34.02",
    "name": "Kabupaten Bantul",
    "shortName": "Kab. Bantul",
    "type": "kabupaten",
    "provinceCode": "34",
    "provinceName": "Daerah Istimewa Yogyakarta"
  },
  {
    "code": "34.03",
    "name": "Kabupaten Gunungkidul",
    "shortName": "Kab. Gunungkidul",
    "type": "kabupaten",
    "provinceCode": "34",
    "provinceName": "Daerah Istimewa Yogyakarta"
  },
  {
    "code": "34.04",
    "name": "Kabupaten Sleman",
    "shortName": "Kab. Sleman",
    "type": "kabupaten",
    "provinceCode": "34",
    "provinceName": "Daerah Istimewa Yogyakarta"
  },
  {
    "code": "34.71",
    "name": "Kota Yogyakarta",
    "shortName": "Yogyakarta",
    "type": "kota",
    "provinceCode": "34",
    "provinceName": "Daerah Istimewa Yogyakarta"
  },
  {
    "code": "35.01",
    "name": "Kabupaten Pacitan",
    "shortName": "Kab. Pacitan",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.02",
    "name": "Kabupaten Ponorogo",
    "shortName": "Kab. Ponorogo",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.03",
    "name": "Kabupaten Trenggalek",
    "shortName": "Kab. Trenggalek",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.04",
    "name": "Kabupaten Tulungagung",
    "shortName": "Kab. Tulungagung",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.05",
    "name": "Kabupaten Blitar",
    "shortName": "Kab. Blitar",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.06",
    "name": "Kabupaten Kediri",
    "shortName": "Kab. Kediri",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.07",
    "name": "Kabupaten Malang",
    "shortName": "Kab. Malang",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.08",
    "name": "Kabupaten Lumajang",
    "shortName": "Kab. Lumajang",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.09",
    "name": "Kabupaten Jember",
    "shortName": "Kab. Jember",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.10",
    "name": "Kabupaten Banyuwangi",
    "shortName": "Kab. Banyuwangi",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.11",
    "name": "Kabupaten Bondowoso",
    "shortName": "Kab. Bondowoso",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.12",
    "name": "Kabupaten Situbondo",
    "shortName": "Kab. Situbondo",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.13",
    "name": "Kabupaten Probolinggo",
    "shortName": "Kab. Probolinggo",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.14",
    "name": "Kabupaten Pasuruan",
    "shortName": "Kab. Pasuruan",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.15",
    "name": "Kabupaten Sidoarjo",
    "shortName": "Kab. Sidoarjo",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.16",
    "name": "Kabupaten Mojokerto",
    "shortName": "Kab. Mojokerto",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.17",
    "name": "Kabupaten Jombang",
    "shortName": "Kab. Jombang",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.18",
    "name": "Kabupaten Nganjuk",
    "shortName": "Kab. Nganjuk",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.19",
    "name": "Kabupaten Madiun",
    "shortName": "Kab. Madiun",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.20",
    "name": "Kabupaten Magetan",
    "shortName": "Kab. Magetan",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.21",
    "name": "Kabupaten Ngawi",
    "shortName": "Kab. Ngawi",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.22",
    "name": "Kabupaten Bojonegoro",
    "shortName": "Kab. Bojonegoro",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.23",
    "name": "Kabupaten Tuban",
    "shortName": "Kab. Tuban",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.24",
    "name": "Kabupaten Lamongan",
    "shortName": "Kab. Lamongan",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.25",
    "name": "Kabupaten Gresik",
    "shortName": "Kab. Gresik",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.26",
    "name": "Kabupaten Bangkalan",
    "shortName": "Kab. Bangkalan",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.27",
    "name": "Kabupaten Sampang",
    "shortName": "Kab. Sampang",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.28",
    "name": "Kabupaten Pamekasan",
    "shortName": "Kab. Pamekasan",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.29",
    "name": "Kabupaten Sumenep",
    "shortName": "Kab. Sumenep",
    "type": "kabupaten",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.71",
    "name": "Kota Kediri",
    "shortName": "Kediri",
    "type": "kota",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.72",
    "name": "Kota Blitar",
    "shortName": "Blitar",
    "type": "kota",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.73",
    "name": "Kota Malang",
    "shortName": "Malang",
    "type": "kota",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.74",
    "name": "Kota Probolinggo",
    "shortName": "Probolinggo",
    "type": "kota",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.75",
    "name": "Kota Pasuruan",
    "shortName": "Pasuruan",
    "type": "kota",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.76",
    "name": "Kota Mojokerto",
    "shortName": "Mojokerto",
    "type": "kota",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.77",
    "name": "Kota Madiun",
    "shortName": "Madiun",
    "type": "kota",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.78",
    "name": "Kota Surabaya",
    "shortName": "Surabaya",
    "type": "kota",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "35.79",
    "name": "Kota Batu",
    "shortName": "Batu",
    "type": "kota",
    "provinceCode": "35",
    "provinceName": "Jawa Timur"
  },
  {
    "code": "36.01",
    "name": "Kabupaten Pandeglang",
    "shortName": "Kab. Pandeglang",
    "type": "kabupaten",
    "provinceCode": "36",
    "provinceName": "Banten"
  },
  {
    "code": "36.02",
    "name": "Kabupaten Lebak",
    "shortName": "Kab. Lebak",
    "type": "kabupaten",
    "provinceCode": "36",
    "provinceName": "Banten"
  },
  {
    "code": "36.03",
    "name": "Kabupaten Tangerang",
    "shortName": "Kab. Tangerang",
    "type": "kabupaten",
    "provinceCode": "36",
    "provinceName": "Banten"
  },
  {
    "code": "36.04",
    "name": "Kabupaten Serang",
    "shortName": "Kab. Serang",
    "type": "kabupaten",
    "provinceCode": "36",
    "provinceName": "Banten"
  },
  {
    "code": "36.71",
    "name": "Kota Tangerang",
    "shortName": "Tangerang",
    "type": "kota",
    "provinceCode": "36",
    "provinceName": "Banten"
  },
  {
    "code": "36.72",
    "name": "Kota Cilegon",
    "shortName": "Cilegon",
    "type": "kota",
    "provinceCode": "36",
    "provinceName": "Banten"
  },
  {
    "code": "36.73",
    "name": "Kota Serang",
    "shortName": "Serang",
    "type": "kota",
    "provinceCode": "36",
    "provinceName": "Banten"
  },
  {
    "code": "36.74",
    "name": "Kota Tangerang Selatan",
    "shortName": "Tangerang Selatan",
    "type": "kota",
    "provinceCode": "36",
    "provinceName": "Banten"
  },
  {
    "code": "51.01",
    "name": "Kabupaten Jembrana",
    "shortName": "Kab. Jembrana",
    "type": "kabupaten",
    "provinceCode": "51",
    "provinceName": "Bali"
  },
  {
    "code": "51.02",
    "name": "Kabupaten Tabanan",
    "shortName": "Kab. Tabanan",
    "type": "kabupaten",
    "provinceCode": "51",
    "provinceName": "Bali"
  },
  {
    "code": "51.03",
    "name": "Kabupaten Badung",
    "shortName": "Kab. Badung",
    "type": "kabupaten",
    "provinceCode": "51",
    "provinceName": "Bali"
  },
  {
    "code": "51.04",
    "name": "Kabupaten Gianyar",
    "shortName": "Kab. Gianyar",
    "type": "kabupaten",
    "provinceCode": "51",
    "provinceName": "Bali"
  },
  {
    "code": "51.05",
    "name": "Kabupaten Klungkung",
    "shortName": "Kab. Klungkung",
    "type": "kabupaten",
    "provinceCode": "51",
    "provinceName": "Bali"
  },
  {
    "code": "51.06",
    "name": "Kabupaten Bangli",
    "shortName": "Kab. Bangli",
    "type": "kabupaten",
    "provinceCode": "51",
    "provinceName": "Bali"
  },
  {
    "code": "51.07",
    "name": "Kabupaten Karangasem",
    "shortName": "Kab. Karangasem",
    "type": "kabupaten",
    "provinceCode": "51",
    "provinceName": "Bali"
  },
  {
    "code": "51.08",
    "name": "Kabupaten Buleleng",
    "shortName": "Kab. Buleleng",
    "type": "kabupaten",
    "provinceCode": "51",
    "provinceName": "Bali"
  },
  {
    "code": "51.71",
    "name": "Kota Denpasar",
    "shortName": "Denpasar",
    "type": "kota",
    "provinceCode": "51",
    "provinceName": "Bali"
  },
  {
    "code": "52.01",
    "name": "Kabupaten Lombok Barat",
    "shortName": "Kab. Lombok Barat",
    "type": "kabupaten",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "52.02",
    "name": "Kabupaten Lombok Tengah",
    "shortName": "Kab. Lombok Tengah",
    "type": "kabupaten",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "52.03",
    "name": "Kabupaten Lombok Timur",
    "shortName": "Kab. Lombok Timur",
    "type": "kabupaten",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "52.04",
    "name": "Kabupaten Sumbawa",
    "shortName": "Kab. Sumbawa",
    "type": "kabupaten",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "52.05",
    "name": "Kabupaten Dompu",
    "shortName": "Kab. Dompu",
    "type": "kabupaten",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "52.06",
    "name": "Kabupaten Bima",
    "shortName": "Kab. Bima",
    "type": "kabupaten",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "52.07",
    "name": "Kabupaten Sumbawa Barat",
    "shortName": "Kab. Sumbawa Barat",
    "type": "kabupaten",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "52.08",
    "name": "Kabupaten Lombok Utara",
    "shortName": "Kab. Lombok Utara",
    "type": "kabupaten",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "52.71",
    "name": "Kota Mataram",
    "shortName": "Mataram",
    "type": "kota",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "52.72",
    "name": "Kota Bima",
    "shortName": "Bima",
    "type": "kota",
    "provinceCode": "52",
    "provinceName": "Nusa Tenggara Barat"
  },
  {
    "code": "53.01",
    "name": "Kabupaten Kupang",
    "shortName": "Kab. Kupang",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.02",
    "name": "Kabupaten Timor Tengah Selatan",
    "shortName": "Kab. Timor Tengah Selatan",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.03",
    "name": "Kabupaten Timor Tengah Utara",
    "shortName": "Kab. Timor Tengah Utara",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.04",
    "name": "Kabupaten Belu",
    "shortName": "Kab. Belu",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.05",
    "name": "Kabupaten Alor",
    "shortName": "Kab. Alor",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.06",
    "name": "Kabupaten Flores Timur",
    "shortName": "Kab. Flores Timur",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.07",
    "name": "Kabupaten Sikka",
    "shortName": "Kab. Sikka",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.08",
    "name": "Kabupaten Ende",
    "shortName": "Kab. Ende",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.09",
    "name": "Kabupaten Ngada",
    "shortName": "Kab. Ngada",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.10",
    "name": "Kabupaten Manggarai",
    "shortName": "Kab. Manggarai",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.11",
    "name": "Kabupaten Sumba Timur",
    "shortName": "Kab. Sumba Timur",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.12",
    "name": "Kabupaten Sumba Barat",
    "shortName": "Kab. Sumba Barat",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.13",
    "name": "Kabupaten Lembata",
    "shortName": "Kab. Lembata",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.14",
    "name": "Kabupaten Rote Ndao",
    "shortName": "Kab. Rote Ndao",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.15",
    "name": "Kabupaten Manggarai Barat",
    "shortName": "Kab. Manggarai Barat",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.16",
    "name": "Kabupaten Nagekeo",
    "shortName": "Kab. Nagekeo",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.17",
    "name": "Kabupaten Sumba Tengah",
    "shortName": "Kab. Sumba Tengah",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.18",
    "name": "Kabupaten Sumba Barat Daya",
    "shortName": "Kab. Sumba Barat Daya",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.19",
    "name": "Kabupaten Manggarai Timur",
    "shortName": "Kab. Manggarai Timur",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.20",
    "name": "Kabupaten Sabu Raijua",
    "shortName": "Kab. Sabu Raijua",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.21",
    "name": "Kabupaten Malaka",
    "shortName": "Kab. Malaka",
    "type": "kabupaten",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "53.71",
    "name": "Kota Kupang",
    "shortName": "Kupang",
    "type": "kota",
    "provinceCode": "53",
    "provinceName": "Nusa Tenggara Timur"
  },
  {
    "code": "61.01",
    "name": "Kabupaten Sambas",
    "shortName": "Kab. Sambas",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.02",
    "name": "Kabupaten Mempawah",
    "shortName": "Kab. Mempawah",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.03",
    "name": "Kabupaten Sanggau",
    "shortName": "Kab. Sanggau",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.04",
    "name": "Kabupaten Ketapang",
    "shortName": "Kab. Ketapang",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.05",
    "name": "Kabupaten Sintang",
    "shortName": "Kab. Sintang",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.06",
    "name": "Kabupaten Kapuas Hulu",
    "shortName": "Kab. Kapuas Hulu",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.07",
    "name": "Kabupaten Bengkayang",
    "shortName": "Kab. Bengkayang",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.08",
    "name": "Kabupaten Landak",
    "shortName": "Kab. Landak",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.09",
    "name": "Kabupaten Sekadau",
    "shortName": "Kab. Sekadau",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.10",
    "name": "Kabupaten Melawi",
    "shortName": "Kab. Melawi",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.11",
    "name": "Kabupaten Kayong Utara",
    "shortName": "Kab. Kayong Utara",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.12",
    "name": "Kabupaten Kubu Raya",
    "shortName": "Kab. Kubu Raya",
    "type": "kabupaten",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.71",
    "name": "Kota Pontianak",
    "shortName": "Pontianak",
    "type": "kota",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "61.72",
    "name": "Kota Singkawang",
    "shortName": "Singkawang",
    "type": "kota",
    "provinceCode": "61",
    "provinceName": "Kalimantan Barat"
  },
  {
    "code": "62.01",
    "name": "Kabupaten Kotawaringin Barat",
    "shortName": "Kab. Kotawaringin Barat",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.02",
    "name": "Kabupaten Kotawaringin Timur",
    "shortName": "Kab. Kotawaringin Timur",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.03",
    "name": "Kabupaten Kapuas",
    "shortName": "Kab. Kapuas",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.04",
    "name": "Kabupaten Barito Selatan",
    "shortName": "Kab. Barito Selatan",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.05",
    "name": "Kabupaten Barito Utara",
    "shortName": "Kab. Barito Utara",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.06",
    "name": "Kabupaten Katingan",
    "shortName": "Kab. Katingan",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.07",
    "name": "Kabupaten Seruyan",
    "shortName": "Kab. Seruyan",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.08",
    "name": "Kabupaten Sukamara",
    "shortName": "Kab. Sukamara",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.09",
    "name": "Kabupaten Lamandau",
    "shortName": "Kab. Lamandau",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.10",
    "name": "Kabupaten Gunung Mas",
    "shortName": "Kab. Gunung Mas",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.11",
    "name": "Kabupaten Pulang Pisau",
    "shortName": "Kab. Pulang Pisau",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.12",
    "name": "Kabupaten Murung Raya",
    "shortName": "Kab. Murung Raya",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.13",
    "name": "Kabupaten Barito Timur",
    "shortName": "Kab. Barito Timur",
    "type": "kabupaten",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "62.71",
    "name": "Kota Palangkaraya",
    "shortName": "Palangkaraya",
    "type": "kota",
    "provinceCode": "62",
    "provinceName": "Kalimantan Tengah"
  },
  {
    "code": "63.01",
    "name": "Kabupaten Tanah Laut",
    "shortName": "Kab. Tanah Laut",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.02",
    "name": "Kabupaten Kotabaru",
    "shortName": "Kab. Kotabaru",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.03",
    "name": "Kabupaten Banjar",
    "shortName": "Kab. Banjar",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.04",
    "name": "Kabupaten Barito Kuala",
    "shortName": "Kab. Barito Kuala",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.05",
    "name": "Kabupaten Tapin",
    "shortName": "Kab. Tapin",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.06",
    "name": "Kabupaten Hulu Sungai Selatan",
    "shortName": "Kab. Hulu Sungai Selatan",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.07",
    "name": "Kabupaten Hulu Sungai Tengah",
    "shortName": "Kab. Hulu Sungai Tengah",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.08",
    "name": "Kabupaten Hulu Sungai Utara",
    "shortName": "Kab. Hulu Sungai Utara",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.09",
    "name": "Kabupaten Tabalong",
    "shortName": "Kab. Tabalong",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.10",
    "name": "Kabupaten Tanah Bumbu",
    "shortName": "Kab. Tanah Bumbu",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.11",
    "name": "Kabupaten Balangan",
    "shortName": "Kab. Balangan",
    "type": "kabupaten",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.71",
    "name": "Kota Banjarmasin",
    "shortName": "Banjarmasin",
    "type": "kota",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "63.72",
    "name": "Kota Banjarbaru",
    "shortName": "Banjarbaru",
    "type": "kota",
    "provinceCode": "63",
    "provinceName": "Kalimantan Selatan"
  },
  {
    "code": "64.01",
    "name": "Kabupaten Paser",
    "shortName": "Kab. Paser",
    "type": "kabupaten",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "64.02",
    "name": "Kabupaten Kutai Kartanegara",
    "shortName": "Kab. Kutai Kartanegara",
    "type": "kabupaten",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "64.03",
    "name": "Kabupaten Berau",
    "shortName": "Kab. Berau",
    "type": "kabupaten",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "64.07",
    "name": "Kabupaten Kutai Barat",
    "shortName": "Kab. Kutai Barat",
    "type": "kabupaten",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "64.08",
    "name": "Kabupaten Kutai Timur",
    "shortName": "Kab. Kutai Timur",
    "type": "kabupaten",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "64.09",
    "name": "Kabupaten Penajam Paser Utara",
    "shortName": "Kab. Penajam Paser Utara",
    "type": "kabupaten",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "64.11",
    "name": "Kabupaten Mahakam Ulu",
    "shortName": "Kab. Mahakam Ulu",
    "type": "kabupaten",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "64.71",
    "name": "Kota Balikpapan",
    "shortName": "Balikpapan",
    "type": "kota",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "64.72",
    "name": "Kota Samarinda",
    "shortName": "Samarinda",
    "type": "kota",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "64.74",
    "name": "Kota Bontang",
    "shortName": "Bontang",
    "type": "kota",
    "provinceCode": "64",
    "provinceName": "Kalimantan Timur"
  },
  {
    "code": "65.01",
    "name": "Kabupaten Bulungan",
    "shortName": "Kab. Bulungan",
    "type": "kabupaten",
    "provinceCode": "65",
    "provinceName": "Kalimantan Utara"
  },
  {
    "code": "65.02",
    "name": "Kabupaten Malinau",
    "shortName": "Kab. Malinau",
    "type": "kabupaten",
    "provinceCode": "65",
    "provinceName": "Kalimantan Utara"
  },
  {
    "code": "65.03",
    "name": "Kabupaten Nunukan",
    "shortName": "Kab. Nunukan",
    "type": "kabupaten",
    "provinceCode": "65",
    "provinceName": "Kalimantan Utara"
  },
  {
    "code": "65.04",
    "name": "Kabupaten Tana Tidung",
    "shortName": "Kab. Tana Tidung",
    "type": "kabupaten",
    "provinceCode": "65",
    "provinceName": "Kalimantan Utara"
  },
  {
    "code": "65.71",
    "name": "Kota Tarakan",
    "shortName": "Tarakan",
    "type": "kota",
    "provinceCode": "65",
    "provinceName": "Kalimantan Utara"
  },
  {
    "code": "71.01",
    "name": "Kabupaten Bolaang Mongondow",
    "shortName": "Kab. Bolaang Mongondow",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.02",
    "name": "Kabupaten Minahasa",
    "shortName": "Kab. Minahasa",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.03",
    "name": "Kabupaten Kepulauan Sangihe",
    "shortName": "Kab. Kepulauan Sangihe",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.04",
    "name": "Kabupaten Kepulauan Talaud",
    "shortName": "Kab. Kepulauan Talaud",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.05",
    "name": "Kabupaten Minahasa Selatan",
    "shortName": "Kab. Minahasa Selatan",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.06",
    "name": "Kabupaten Minahasa Utara",
    "shortName": "Kab. Minahasa Utara",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.07",
    "name": "Kabupaten Minahasa Tenggara",
    "shortName": "Kab. Minahasa Tenggara",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.08",
    "name": "Kabupaten Bolaang Mongondow Utara",
    "shortName": "Kab. Bolaang Mongondow Utara",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.09",
    "name": "Kabupaten Kep. Siau Tagulandang Biaro",
    "shortName": "Kab. Kep. Siau Tagulandang Biaro",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.10",
    "name": "Kabupaten Bolaang Mongondow Timur",
    "shortName": "Kab. Bolaang Mongondow Timur",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.11",
    "name": "Kabupaten Bolaang Mongondow Selatan",
    "shortName": "Kab. Bolaang Mongondow Selatan",
    "type": "kabupaten",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.71",
    "name": "Kota Manado",
    "shortName": "Manado",
    "type": "kota",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.72",
    "name": "Kota Bitung",
    "shortName": "Bitung",
    "type": "kota",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.73",
    "name": "Kota Tomohon",
    "shortName": "Tomohon",
    "type": "kota",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "71.74",
    "name": "Kota Kotamobagu",
    "shortName": "Kotamobagu",
    "type": "kota",
    "provinceCode": "71",
    "provinceName": "Sulawesi Utara"
  },
  {
    "code": "72.01",
    "name": "Kabupaten Banggai",
    "shortName": "Kab. Banggai",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.02",
    "name": "Kabupaten Poso",
    "shortName": "Kab. Poso",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.03",
    "name": "Kabupaten Donggala",
    "shortName": "Kab. Donggala",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.04",
    "name": "Kabupaten Toli-Toli",
    "shortName": "Kab. Toli-Toli",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.05",
    "name": "Kabupaten Buol",
    "shortName": "Kab. Buol",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.06",
    "name": "Kabupaten Morowali",
    "shortName": "Kab. Morowali",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.07",
    "name": "Kabupaten Banggai Kepulauan",
    "shortName": "Kab. Banggai Kepulauan",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.08",
    "name": "Kabupaten Parigi Moutong",
    "shortName": "Kab. Parigi Moutong",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.09",
    "name": "Kabupaten Tojo Una Una",
    "shortName": "Kab. Tojo Una Una",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.10",
    "name": "Kabupaten Sigi",
    "shortName": "Kab. Sigi",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.11",
    "name": "Kabupaten Banggai Laut",
    "shortName": "Kab. Banggai Laut",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.12",
    "name": "Kabupaten Morowali Utara",
    "shortName": "Kab. Morowali Utara",
    "type": "kabupaten",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "72.71",
    "name": "Kota Palu",
    "shortName": "Palu",
    "type": "kota",
    "provinceCode": "72",
    "provinceName": "Sulawesi Tengah"
  },
  {
    "code": "73.01",
    "name": "Kabupaten Kepulauan Selayar",
    "shortName": "Kab. Kepulauan Selayar",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.02",
    "name": "Kabupaten Bulukumba",
    "shortName": "Kab. Bulukumba",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.03",
    "name": "Kabupaten Bantaeng",
    "shortName": "Kab. Bantaeng",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.04",
    "name": "Kabupaten Jeneponto",
    "shortName": "Kab. Jeneponto",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.05",
    "name": "Kabupaten Takalar",
    "shortName": "Kab. Takalar",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.06",
    "name": "Kabupaten Gowa",
    "shortName": "Kab. Gowa",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.07",
    "name": "Kabupaten Sinjai",
    "shortName": "Kab. Sinjai",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.08",
    "name": "Kabupaten Bone",
    "shortName": "Kab. Bone",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.09",
    "name": "Kabupaten Maros",
    "shortName": "Kab. Maros",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.10",
    "name": "Kabupaten Pangkajene dan Kepulauan",
    "shortName": "Kab. Pangkajene dan Kepulauan",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.11",
    "name": "Kabupaten Barru",
    "shortName": "Kab. Barru",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.12",
    "name": "Kabupaten Soppeng",
    "shortName": "Kab. Soppeng",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.13",
    "name": "Kabupaten Wajo",
    "shortName": "Kab. Wajo",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.14",
    "name": "Kabupaten Sidenreng Rappang",
    "shortName": "Kab. Sidenreng Rappang",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.15",
    "name": "Kabupaten Pinrang",
    "shortName": "Kab. Pinrang",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.16",
    "name": "Kabupaten Enrekang",
    "shortName": "Kab. Enrekang",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.17",
    "name": "Kabupaten Luwu",
    "shortName": "Kab. Luwu",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.18",
    "name": "Kabupaten Tana Toraja",
    "shortName": "Kab. Tana Toraja",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.22",
    "name": "Kabupaten Luwu Utara",
    "shortName": "Kab. Luwu Utara",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.24",
    "name": "Kabupaten Luwu Timur",
    "shortName": "Kab. Luwu Timur",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.26",
    "name": "Kabupaten Toraja Utara",
    "shortName": "Kab. Toraja Utara",
    "type": "kabupaten",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.71",
    "name": "Kota Makassar",
    "shortName": "Makassar",
    "type": "kota",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.72",
    "name": "Kota Parepare",
    "shortName": "Parepare",
    "type": "kota",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "73.73",
    "name": "Kota Palopo",
    "shortName": "Palopo",
    "type": "kota",
    "provinceCode": "73",
    "provinceName": "Sulawesi Selatan"
  },
  {
    "code": "74.01",
    "name": "Kabupaten Kolaka",
    "shortName": "Kab. Kolaka",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.02",
    "name": "Kabupaten Konawe",
    "shortName": "Kab. Konawe",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.03",
    "name": "Kabupaten Muna",
    "shortName": "Kab. Muna",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.04",
    "name": "Kabupaten Buton",
    "shortName": "Kab. Buton",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.05",
    "name": "Kabupaten Konawe Selatan",
    "shortName": "Kab. Konawe Selatan",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.06",
    "name": "Kabupaten Bombana",
    "shortName": "Kab. Bombana",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.07",
    "name": "Kabupaten Wakatobi",
    "shortName": "Kab. Wakatobi",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.08",
    "name": "Kabupaten Kolaka Utara",
    "shortName": "Kab. Kolaka Utara",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.09",
    "name": "Kabupaten Konawe Utara",
    "shortName": "Kab. Konawe Utara",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.10",
    "name": "Kabupaten Buton Utara",
    "shortName": "Kab. Buton Utara",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.11",
    "name": "Kabupaten Kolaka Timur",
    "shortName": "Kab. Kolaka Timur",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.12",
    "name": "Kabupaten Konawe Kepulauan",
    "shortName": "Kab. Konawe Kepulauan",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.13",
    "name": "Kabupaten Muna Barat",
    "shortName": "Kab. Muna Barat",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.14",
    "name": "Kabupaten Buton Tengah",
    "shortName": "Kab. Buton Tengah",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.15",
    "name": "Kabupaten Buton Selatan",
    "shortName": "Kab. Buton Selatan",
    "type": "kabupaten",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.71",
    "name": "Kota Kendari",
    "shortName": "Kendari",
    "type": "kota",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "74.72",
    "name": "Kota Bau Bau",
    "shortName": "Bau Bau",
    "type": "kota",
    "provinceCode": "74",
    "provinceName": "Sulawesi Tenggara"
  },
  {
    "code": "75.01",
    "name": "Kabupaten Gorontalo",
    "shortName": "Kab. Gorontalo",
    "type": "kabupaten",
    "provinceCode": "75",
    "provinceName": "Gorontalo"
  },
  {
    "code": "75.02",
    "name": "Kabupaten Boalemo",
    "shortName": "Kab. Boalemo",
    "type": "kabupaten",
    "provinceCode": "75",
    "provinceName": "Gorontalo"
  },
  {
    "code": "75.03",
    "name": "Kabupaten Bone Bolango",
    "shortName": "Kab. Bone Bolango",
    "type": "kabupaten",
    "provinceCode": "75",
    "provinceName": "Gorontalo"
  },
  {
    "code": "75.04",
    "name": "Kabupaten Pohuwato",
    "shortName": "Kab. Pohuwato",
    "type": "kabupaten",
    "provinceCode": "75",
    "provinceName": "Gorontalo"
  },
  {
    "code": "75.05",
    "name": "Kabupaten Gorontalo Utara",
    "shortName": "Kab. Gorontalo Utara",
    "type": "kabupaten",
    "provinceCode": "75",
    "provinceName": "Gorontalo"
  },
  {
    "code": "75.71",
    "name": "Kota Gorontalo",
    "shortName": "Gorontalo",
    "type": "kota",
    "provinceCode": "75",
    "provinceName": "Gorontalo"
  },
  {
    "code": "76.01",
    "name": "Kabupaten Pasangkayu",
    "shortName": "Kab. Pasangkayu",
    "type": "kabupaten",
    "provinceCode": "76",
    "provinceName": "Sulawesi Barat"
  },
  {
    "code": "76.02",
    "name": "Kabupaten Mamuju",
    "shortName": "Kab. Mamuju",
    "type": "kabupaten",
    "provinceCode": "76",
    "provinceName": "Sulawesi Barat"
  },
  {
    "code": "76.03",
    "name": "Kabupaten Mamasa",
    "shortName": "Kab. Mamasa",
    "type": "kabupaten",
    "provinceCode": "76",
    "provinceName": "Sulawesi Barat"
  },
  {
    "code": "76.04",
    "name": "Kabupaten Polewali Mandar",
    "shortName": "Kab. Polewali Mandar",
    "type": "kabupaten",
    "provinceCode": "76",
    "provinceName": "Sulawesi Barat"
  },
  {
    "code": "76.05",
    "name": "Kabupaten Majene",
    "shortName": "Kab. Majene",
    "type": "kabupaten",
    "provinceCode": "76",
    "provinceName": "Sulawesi Barat"
  },
  {
    "code": "76.06",
    "name": "Kabupaten Mamuju Tengah",
    "shortName": "Kab. Mamuju Tengah",
    "type": "kabupaten",
    "provinceCode": "76",
    "provinceName": "Sulawesi Barat"
  },
  {
    "code": "81.01",
    "name": "Kabupaten Maluku Tengah",
    "shortName": "Kab. Maluku Tengah",
    "type": "kabupaten",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.02",
    "name": "Kabupaten Maluku Tenggara",
    "shortName": "Kab. Maluku Tenggara",
    "type": "kabupaten",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.03",
    "name": "Kabupaten Kepulauan Tanimbar",
    "shortName": "Kab. Kepulauan Tanimbar",
    "type": "kabupaten",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.04",
    "name": "Kabupaten Buru",
    "shortName": "Kab. Buru",
    "type": "kabupaten",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.05",
    "name": "Kabupaten Seram Bagian Timur",
    "shortName": "Kab. Seram Bagian Timur",
    "type": "kabupaten",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.06",
    "name": "Kabupaten Seram Bagian Barat",
    "shortName": "Kab. Seram Bagian Barat",
    "type": "kabupaten",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.07",
    "name": "Kabupaten Kepulauan Aru",
    "shortName": "Kab. Kepulauan Aru",
    "type": "kabupaten",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.08",
    "name": "Kabupaten Maluku Barat Daya",
    "shortName": "Kab. Maluku Barat Daya",
    "type": "kabupaten",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.09",
    "name": "Kabupaten Buru Selatan",
    "shortName": "Kab. Buru Selatan",
    "type": "kabupaten",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.71",
    "name": "Kota Ambon",
    "shortName": "Ambon",
    "type": "kota",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "81.72",
    "name": "Kota Tual",
    "shortName": "Tual",
    "type": "kota",
    "provinceCode": "81",
    "provinceName": "Maluku"
  },
  {
    "code": "82.01",
    "name": "Kabupaten Halmahera Barat",
    "shortName": "Kab. Halmahera Barat",
    "type": "kabupaten",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "82.02",
    "name": "Kabupaten Halmahera Tengah",
    "shortName": "Kab. Halmahera Tengah",
    "type": "kabupaten",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "82.03",
    "name": "Kabupaten Halmahera Utara",
    "shortName": "Kab. Halmahera Utara",
    "type": "kabupaten",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "82.04",
    "name": "Kabupaten Halmahera Selatan",
    "shortName": "Kab. Halmahera Selatan",
    "type": "kabupaten",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "82.05",
    "name": "Kabupaten Kepulauan Sula",
    "shortName": "Kab. Kepulauan Sula",
    "type": "kabupaten",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "82.06",
    "name": "Kabupaten Halmahera Timur",
    "shortName": "Kab. Halmahera Timur",
    "type": "kabupaten",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "82.07",
    "name": "Kabupaten Pulau Morotai",
    "shortName": "Kab. Pulau Morotai",
    "type": "kabupaten",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "82.08",
    "name": "Kabupaten Pulau Taliabu",
    "shortName": "Kab. Pulau Taliabu",
    "type": "kabupaten",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "82.71",
    "name": "Kota Ternate",
    "shortName": "Ternate",
    "type": "kota",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "82.72",
    "name": "Kota Tidore Kepulauan",
    "shortName": "Tidore Kepulauan",
    "type": "kota",
    "provinceCode": "82",
    "provinceName": "Maluku Utara"
  },
  {
    "code": "91.03",
    "name": "Kabupaten Jayapura",
    "shortName": "Kab. Jayapura",
    "type": "kabupaten",
    "provinceCode": "91",
    "provinceName": "Papua"
  },
  {
    "code": "91.05",
    "name": "Kabupaten Kepulauan Yapen",
    "shortName": "Kab. Kepulauan Yapen",
    "type": "kabupaten",
    "provinceCode": "91",
    "provinceName": "Papua"
  },
  {
    "code": "91.06",
    "name": "Kabupaten Biak Numfor",
    "shortName": "Kab. Biak Numfor",
    "type": "kabupaten",
    "provinceCode": "91",
    "provinceName": "Papua"
  },
  {
    "code": "91.10",
    "name": "Kabupaten Sarmi",
    "shortName": "Kab. Sarmi",
    "type": "kabupaten",
    "provinceCode": "91",
    "provinceName": "Papua"
  },
  {
    "code": "91.11",
    "name": "Kabupaten Keerom",
    "shortName": "Kab. Keerom",
    "type": "kabupaten",
    "provinceCode": "91",
    "provinceName": "Papua"
  },
  {
    "code": "91.15",
    "name": "Kabupaten Waropen",
    "shortName": "Kab. Waropen",
    "type": "kabupaten",
    "provinceCode": "91",
    "provinceName": "Papua"
  },
  {
    "code": "91.19",
    "name": "Kabupaten Supiori",
    "shortName": "Kab. Supiori",
    "type": "kabupaten",
    "provinceCode": "91",
    "provinceName": "Papua"
  },
  {
    "code": "91.20",
    "name": "Kabupaten Mamberamo Raya",
    "shortName": "Kab. Mamberamo Raya",
    "type": "kabupaten",
    "provinceCode": "91",
    "provinceName": "Papua"
  },
  {
    "code": "91.71",
    "name": "Kota Jayapura",
    "shortName": "Jayapura",
    "type": "kota",
    "provinceCode": "91",
    "provinceName": "Papua"
  },
  {
    "code": "92.02",
    "name": "Kabupaten Manokwari",
    "shortName": "Kab. Manokwari",
    "type": "kabupaten",
    "provinceCode": "92",
    "provinceName": "Papua Barat"
  },
  {
    "code": "92.03",
    "name": "Kabupaten Fak Fak",
    "shortName": "Kab. Fak Fak",
    "type": "kabupaten",
    "provinceCode": "92",
    "provinceName": "Papua Barat"
  },
  {
    "code": "92.06",
    "name": "Kabupaten Teluk Bintuni",
    "shortName": "Kab. Teluk Bintuni",
    "type": "kabupaten",
    "provinceCode": "92",
    "provinceName": "Papua Barat"
  },
  {
    "code": "92.07",
    "name": "Kabupaten Teluk Wondama",
    "shortName": "Kab. Teluk Wondama",
    "type": "kabupaten",
    "provinceCode": "92",
    "provinceName": "Papua Barat"
  },
  {
    "code": "92.08",
    "name": "Kabupaten Kaimana",
    "shortName": "Kab. Kaimana",
    "type": "kabupaten",
    "provinceCode": "92",
    "provinceName": "Papua Barat"
  },
  {
    "code": "92.11",
    "name": "Kabupaten Manokwari Selatan",
    "shortName": "Kab. Manokwari Selatan",
    "type": "kabupaten",
    "provinceCode": "92",
    "provinceName": "Papua Barat"
  },
  {
    "code": "92.12",
    "name": "Kabupaten Pegunungan Arfak",
    "shortName": "Kab. Pegunungan Arfak",
    "type": "kabupaten",
    "provinceCode": "92",
    "provinceName": "Papua Barat"
  },
  {
    "code": "93.01",
    "name": "Kabupaten Merauke",
    "shortName": "Kab. Merauke",
    "type": "kabupaten",
    "provinceCode": "93",
    "provinceName": "Papua Selatan"
  },
  {
    "code": "93.02",
    "name": "Kabupaten Boven Digoel",
    "shortName": "Kab. Boven Digoel",
    "type": "kabupaten",
    "provinceCode": "93",
    "provinceName": "Papua Selatan"
  },
  {
    "code": "93.03",
    "name": "Kabupaten Mappi",
    "shortName": "Kab. Mappi",
    "type": "kabupaten",
    "provinceCode": "93",
    "provinceName": "Papua Selatan"
  },
  {
    "code": "93.04",
    "name": "Kabupaten Asmat",
    "shortName": "Kab. Asmat",
    "type": "kabupaten",
    "provinceCode": "93",
    "provinceName": "Papua Selatan"
  },
  {
    "code": "94.01",
    "name": "Kabupaten Nabire",
    "shortName": "Kab. Nabire",
    "type": "kabupaten",
    "provinceCode": "94",
    "provinceName": "Papua Tengah"
  },
  {
    "code": "94.02",
    "name": "Kabupaten Puncak Jaya",
    "shortName": "Kab. Puncak Jaya",
    "type": "kabupaten",
    "provinceCode": "94",
    "provinceName": "Papua Tengah"
  },
  {
    "code": "94.03",
    "name": "Kabupaten Paniai",
    "shortName": "Kab. Paniai",
    "type": "kabupaten",
    "provinceCode": "94",
    "provinceName": "Papua Tengah"
  },
  {
    "code": "94.04",
    "name": "Kabupaten Mimika",
    "shortName": "Kab. Mimika",
    "type": "kabupaten",
    "provinceCode": "94",
    "provinceName": "Papua Tengah"
  },
  {
    "code": "94.05",
    "name": "Kabupaten Puncak",
    "shortName": "Kab. Puncak",
    "type": "kabupaten",
    "provinceCode": "94",
    "provinceName": "Papua Tengah"
  },
  {
    "code": "94.06",
    "name": "Kabupaten Dogiyai",
    "shortName": "Kab. Dogiyai",
    "type": "kabupaten",
    "provinceCode": "94",
    "provinceName": "Papua Tengah"
  },
  {
    "code": "94.07",
    "name": "Kabupaten Intan Jaya",
    "shortName": "Kab. Intan Jaya",
    "type": "kabupaten",
    "provinceCode": "94",
    "provinceName": "Papua Tengah"
  },
  {
    "code": "94.08",
    "name": "Kabupaten Deiyai",
    "shortName": "Kab. Deiyai",
    "type": "kabupaten",
    "provinceCode": "94",
    "provinceName": "Papua Tengah"
  },
  {
    "code": "95.01",
    "name": "Kabupaten Jayawijaya",
    "shortName": "Kab. Jayawijaya",
    "type": "kabupaten",
    "provinceCode": "95",
    "provinceName": "Papua Pegunungan"
  },
  {
    "code": "95.02",
    "name": "Kabupaten Pegunungan Bintang",
    "shortName": "Kab. Pegunungan Bintang",
    "type": "kabupaten",
    "provinceCode": "95",
    "provinceName": "Papua Pegunungan"
  },
  {
    "code": "95.03",
    "name": "Kabupaten Yahukimo",
    "shortName": "Kab. Yahukimo",
    "type": "kabupaten",
    "provinceCode": "95",
    "provinceName": "Papua Pegunungan"
  },
  {
    "code": "95.04",
    "name": "Kabupaten Tolikara",
    "shortName": "Kab. Tolikara",
    "type": "kabupaten",
    "provinceCode": "95",
    "provinceName": "Papua Pegunungan"
  },
  {
    "code": "95.05",
    "name": "Kabupaten Mamberamo Tengah",
    "shortName": "Kab. Mamberamo Tengah",
    "type": "kabupaten",
    "provinceCode": "95",
    "provinceName": "Papua Pegunungan"
  },
  {
    "code": "95.06",
    "name": "Kabupaten Yalimo",
    "shortName": "Kab. Yalimo",
    "type": "kabupaten",
    "provinceCode": "95",
    "provinceName": "Papua Pegunungan"
  },
  {
    "code": "95.07",
    "name": "Kabupaten Lanny Jaya",
    "shortName": "Kab. Lanny Jaya",
    "type": "kabupaten",
    "provinceCode": "95",
    "provinceName": "Papua Pegunungan"
  },
  {
    "code": "95.08",
    "name": "Kabupaten Nduga",
    "shortName": "Kab. Nduga",
    "type": "kabupaten",
    "provinceCode": "95",
    "provinceName": "Papua Pegunungan"
  },
  {
    "code": "96.01",
    "name": "Kabupaten Sorong",
    "shortName": "Kab. Sorong",
    "type": "kabupaten",
    "provinceCode": "96",
    "provinceName": "Papua Barat Daya"
  },
  {
    "code": "96.02",
    "name": "Kabupaten Sorong Selatan",
    "shortName": "Kab. Sorong Selatan",
    "type": "kabupaten",
    "provinceCode": "96",
    "provinceName": "Papua Barat Daya"
  },
  {
    "code": "96.03",
    "name": "Kabupaten Raja Ampat",
    "shortName": "Kab. Raja Ampat",
    "type": "kabupaten",
    "provinceCode": "96",
    "provinceName": "Papua Barat Daya"
  },
  {
    "code": "96.04",
    "name": "Kabupaten Tambrauw",
    "shortName": "Kab. Tambrauw",
    "type": "kabupaten",
    "provinceCode": "96",
    "provinceName": "Papua Barat Daya"
  },
  {
    "code": "96.05",
    "name": "Kabupaten Maybrat",
    "shortName": "Kab. Maybrat",
    "type": "kabupaten",
    "provinceCode": "96",
    "provinceName": "Papua Barat Daya"
  },
  {
    "code": "96.71",
    "name": "Kota Sorong",
    "shortName": "Sorong",
    "type": "kota",
    "provinceCode": "96",
    "provinceName": "Papua Barat Daya"
  }
]
